<Project>
  <Sdk Name="Microsoft.NET.Sdk" />
  <Sdk Name="ktsu.Sdk" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <TargetFrameworks></TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="Spectre.Console.Ansi" />
    <PackageReference Include="DiffPlex" />
    <PackageReference Include="ktsu.AppDataStorage" />
    <PackageReference Include="ktsu.Semantics.Paths" />
    <PackageReference Include="ktsu.Semantics.Strings" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KtsuTools.Core\KtsuTools.Core.csproj" />
  </ItemGroup>

</Project>
